//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7ClientProject.HL7WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", ConfigurationName="HL7WebService.MessageValidationV2Interface")]
    public interface MessageValidationV2Interface {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HL7ClientProject.HL7WebService.validateResponse validate(HL7ClientProject.HL7WebService.validate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateResponse> validateAsync(HL7ClientProject.HL7WebService.validate request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HL7ClientProject.HL7WebService.loadResourceResponse loadResource(HL7ClientProject.HL7WebService.loadResource request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.loadResourceResponse> loadResourceAsync(HL7ClientProject.HL7WebService.loadResource request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HL7ClientProject.HL7WebService.validateDQAResponse validateDQA(HL7ClientProject.HL7WebService.validateDQA request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateDQAResponse> validateDQAAsync(HL7ClientProject.HL7WebService.validateDQA request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HL7ClientProject.HL7WebService.validateWithResourcesResponse validateWithResources(HL7ClientProject.HL7WebService.validateWithResources request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateWithResourcesResponse> validateWithResourcesAsync(HL7ClientProject.HL7WebService.validateWithResources request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        HL7ClientProject.HL7WebService.getServiceStatusResponse getServiceStatus(HL7ClientProject.HL7WebService.getServiceStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.getServiceStatusResponse> getServiceStatusAsync(HL7ClientProject.HL7WebService.getServiceStatus request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validate", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.validateBody Body;
        
        public validate() {
        }
        
        public validate(HL7ClientProject.HL7WebService.validateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        public validateBody() {
        }
        
        public validateBody(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateResponse", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.validateResponseBody Body;
        
        public validateResponse() {
        }
        
        public validateResponse(HL7ClientProject.HL7WebService.validateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validateResponseBody() {
        }
        
        public validateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loadResource {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loadResource", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.loadResourceBody Body;
        
        public loadResource() {
        }
        
        public loadResource(HL7ClientProject.HL7WebService.loadResourceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loadResourceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public loadResourceBody() {
        }
        
        public loadResourceBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loadResourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loadResourceResponse", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.loadResourceResponseBody Body;
        
        public loadResourceResponse() {
        }
        
        public loadResourceResponse(HL7ClientProject.HL7WebService.loadResourceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loadResourceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loadResourceResponseBody() {
        }
        
        public loadResourceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateDQA {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateDQA", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.validateDQABody Body;
        
        public validateDQA() {
        }
        
        public validateDQA(HL7ClientProject.HL7WebService.validateDQABody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateDQABody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        public validateDQABody() {
        }
        
        public validateDQABody(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateDQAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateDQAResponse", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.validateDQAResponseBody Body;
        
        public validateDQAResponse() {
        }
        
        public validateDQAResponse(HL7ClientProject.HL7WebService.validateDQAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateDQAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validateDQAResponseBody() {
        }
        
        public validateDQAResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateWithResources {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateWithResources", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.validateWithResourcesBody Body;
        
        public validateWithResources() {
        }
        
        public validateWithResources(HL7ClientProject.HL7WebService.validateWithResourcesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateWithResourcesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        public validateWithResourcesBody() {
        }
        
        public validateWithResourcesBody(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateWithResourcesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateWithResourcesResponse", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.validateWithResourcesResponseBody Body;
        
        public validateWithResourcesResponse() {
        }
        
        public validateWithResourcesResponse(HL7ClientProject.HL7WebService.validateWithResourcesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateWithResourcesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validateWithResourcesResponseBody() {
        }
        
        public validateWithResourcesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceStatus", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.getServiceStatusBody Body;
        
        public getServiceStatus() {
        }
        
        public getServiceStatus(HL7ClientProject.HL7WebService.getServiceStatusBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getServiceStatusBody {
        
        public getServiceStatusBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceStatusResponse", Namespace="http://messagevalidation.hl7ws.healthcare.nist.gov/", Order=0)]
        public HL7ClientProject.HL7WebService.getServiceStatusResponseBody Body;
        
        public getServiceStatusResponse() {
        }
        
        public getServiceStatusResponse(HL7ClientProject.HL7WebService.getServiceStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getServiceStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getServiceStatusResponseBody() {
        }
        
        public getServiceStatusResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageValidationV2InterfaceChannel : HL7ClientProject.HL7WebService.MessageValidationV2Interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageValidationV2InterfaceClient : System.ServiceModel.ClientBase<HL7ClientProject.HL7WebService.MessageValidationV2Interface>, HL7ClientProject.HL7WebService.MessageValidationV2Interface {
        
        public MessageValidationV2InterfaceClient() {
        }
        
        public MessageValidationV2InterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageValidationV2InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageValidationV2InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageValidationV2InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HL7ClientProject.HL7WebService.validateResponse HL7ClientProject.HL7WebService.MessageValidationV2Interface.validate(HL7ClientProject.HL7WebService.validate request) {
            return base.Channel.validate(request);
        }
        
        public string validate(string arg0, string arg1, string arg2, string arg3) {
            HL7ClientProject.HL7WebService.validate inValue = new HL7ClientProject.HL7WebService.validate();
            inValue.Body = new HL7ClientProject.HL7WebService.validateBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            HL7ClientProject.HL7WebService.validateResponse retVal = ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).validate(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateResponse> HL7ClientProject.HL7WebService.MessageValidationV2Interface.validateAsync(HL7ClientProject.HL7WebService.validate request) {
            return base.Channel.validateAsync(request);
        }
        
        public System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateResponse> validateAsync(string arg0, string arg1, string arg2, string arg3) {
            HL7ClientProject.HL7WebService.validate inValue = new HL7ClientProject.HL7WebService.validate();
            inValue.Body = new HL7ClientProject.HL7WebService.validateBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            return ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).validateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HL7ClientProject.HL7WebService.loadResourceResponse HL7ClientProject.HL7WebService.MessageValidationV2Interface.loadResource(HL7ClientProject.HL7WebService.loadResource request) {
            return base.Channel.loadResource(request);
        }
        
        public string loadResource(string arg0, string arg1, string arg2) {
            HL7ClientProject.HL7WebService.loadResource inValue = new HL7ClientProject.HL7WebService.loadResource();
            inValue.Body = new HL7ClientProject.HL7WebService.loadResourceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            HL7ClientProject.HL7WebService.loadResourceResponse retVal = ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).loadResource(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.loadResourceResponse> HL7ClientProject.HL7WebService.MessageValidationV2Interface.loadResourceAsync(HL7ClientProject.HL7WebService.loadResource request) {
            return base.Channel.loadResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.loadResourceResponse> loadResourceAsync(string arg0, string arg1, string arg2) {
            HL7ClientProject.HL7WebService.loadResource inValue = new HL7ClientProject.HL7WebService.loadResource();
            inValue.Body = new HL7ClientProject.HL7WebService.loadResourceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).loadResourceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HL7ClientProject.HL7WebService.validateDQAResponse HL7ClientProject.HL7WebService.MessageValidationV2Interface.validateDQA(HL7ClientProject.HL7WebService.validateDQA request) {
            return base.Channel.validateDQA(request);
        }
        
        public string validateDQA(string arg0, string arg1, string arg2, string arg3, string arg4) {
            HL7ClientProject.HL7WebService.validateDQA inValue = new HL7ClientProject.HL7WebService.validateDQA();
            inValue.Body = new HL7ClientProject.HL7WebService.validateDQABody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            HL7ClientProject.HL7WebService.validateDQAResponse retVal = ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).validateDQA(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateDQAResponse> HL7ClientProject.HL7WebService.MessageValidationV2Interface.validateDQAAsync(HL7ClientProject.HL7WebService.validateDQA request) {
            return base.Channel.validateDQAAsync(request);
        }
        
        public System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateDQAResponse> validateDQAAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            HL7ClientProject.HL7WebService.validateDQA inValue = new HL7ClientProject.HL7WebService.validateDQA();
            inValue.Body = new HL7ClientProject.HL7WebService.validateDQABody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            return ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).validateDQAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HL7ClientProject.HL7WebService.validateWithResourcesResponse HL7ClientProject.HL7WebService.MessageValidationV2Interface.validateWithResources(HL7ClientProject.HL7WebService.validateWithResources request) {
            return base.Channel.validateWithResources(request);
        }
        
        public string validateWithResources(string arg0, string arg1, string arg2, string arg3, string arg4) {
            HL7ClientProject.HL7WebService.validateWithResources inValue = new HL7ClientProject.HL7WebService.validateWithResources();
            inValue.Body = new HL7ClientProject.HL7WebService.validateWithResourcesBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            HL7ClientProject.HL7WebService.validateWithResourcesResponse retVal = ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).validateWithResources(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateWithResourcesResponse> HL7ClientProject.HL7WebService.MessageValidationV2Interface.validateWithResourcesAsync(HL7ClientProject.HL7WebService.validateWithResources request) {
            return base.Channel.validateWithResourcesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.validateWithResourcesResponse> validateWithResourcesAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            HL7ClientProject.HL7WebService.validateWithResources inValue = new HL7ClientProject.HL7WebService.validateWithResources();
            inValue.Body = new HL7ClientProject.HL7WebService.validateWithResourcesBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            return ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).validateWithResourcesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HL7ClientProject.HL7WebService.getServiceStatusResponse HL7ClientProject.HL7WebService.MessageValidationV2Interface.getServiceStatus(HL7ClientProject.HL7WebService.getServiceStatus request) {
            return base.Channel.getServiceStatus(request);
        }
        
        public string getServiceStatus() {
            HL7ClientProject.HL7WebService.getServiceStatus inValue = new HL7ClientProject.HL7WebService.getServiceStatus();
            inValue.Body = new HL7ClientProject.HL7WebService.getServiceStatusBody();
            HL7ClientProject.HL7WebService.getServiceStatusResponse retVal = ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).getServiceStatus(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.getServiceStatusResponse> HL7ClientProject.HL7WebService.MessageValidationV2Interface.getServiceStatusAsync(HL7ClientProject.HL7WebService.getServiceStatus request) {
            return base.Channel.getServiceStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<HL7ClientProject.HL7WebService.getServiceStatusResponse> getServiceStatusAsync() {
            HL7ClientProject.HL7WebService.getServiceStatus inValue = new HL7ClientProject.HL7WebService.getServiceStatus();
            inValue.Body = new HL7ClientProject.HL7WebService.getServiceStatusBody();
            return ((HL7ClientProject.HL7WebService.MessageValidationV2Interface)(this)).getServiceStatusAsync(inValue);
        }
    }
}
